"""empty message

Revision ID: 0d60e646518c
Revises: 5391b8a670c1
Create Date: 2025-05-09 14:33:50.858489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d60e646518c'
down_revision: Union[str, None] = '5391b8a670c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('applied_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('remote')
        batch_op.drop_column('job_url')
        batch_op.drop_column('status_details')
        batch_op.drop_column('application_method')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_method', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('job_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('remote', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('applied_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
