"""empty message

Revision ID: 7cb7e29ef42a
Revises: 88926e4364a0
Create Date: 2025-05-09 15:06:42.153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb7e29ef42a'
down_revision: Union[str, None] = '88926e4364a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_records', schema=None) as batch_op:
        batch_op.alter_column('change_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key('fk_change_records_application_id_applications', 'applications', ['application_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_change_records_application_id_applications', type_='foreignkey')
        batch_op.alter_column('change_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
