from enum import Enum


class ChangeType(str, Enum):
    """Types of changes that can be recorded."""

    STATUS_CHANGE = "STATUS_CHANGE"
    NOTE_ADDED = "NOTE_ADDED"
    CONTACT_ADDED = "CONTACT_ADDED"
    CONTACT_REMOVED = "CONTACT_REMOVED"
    APPLICATION_UPDATED = "APPLICATION_UPDATED"
    DOCUMENT_ADDED = "DOCUMENT_ADDED"
    INTERACTION_ADDED = "INTERACTION_ADDED"
    INTERACTION_UPDATED = "INTERACTION_UPDATED"
    INTERACTION_DELETED = "INTERACTION_DELETED"
